file_server:
  # serve_path is where the data to be served is located (required)
  serve_path: "/srv/http"
  # base_path is the base path of the web directory ("/histoire" = "http://example.com/histoire/example/path") (optional, defaults to "/")
  #base_path: "/"
  # theme points to a folder with theme files, see README.md for information (optional, defaults to "default")
  #theme: "default"
  # show_dot_files says what it does on the tin (optional, default is false)
  #show_dot_files: false
  # use_interactive_breadcrumb allows you to disable the interactive breadcrumb if it's not to your taste (optional, defaults to true)
  #use_interactive_breadcrumb: true
  # enable_header_files lets you enable or disable reading files in each directory to give a header and footer (optional, defaults to true)
  #enable_header_files: true

  # enable_page_thumbnail enables embed thumbnails for each folder index (optional, default is false, there is some setup required see README.md)
  #enable_page_thumbnail: false
  # enable_image_thumbnail enables image thumbnails (optional, default is false)
  #enable_image_thumbnail: false
  # enable_video_thumbnail enables video thumbnails (optional, default is false)
  #enable_video_thumbnail: false
  # server_url is the URL pointing to your web server excluding the base path (optional, default is "http://127.0.0.1:5000", you NEED to change this)
  #server_url: "http://127.0.0.1:5000"
  # thumbimage_cache_dir and wkhtmltoimage_cache_dir are cache directories for the page thumbnailing (optional, both point to cache/ in the location of configparser.py)
  #thumbimage_cache_dir: "/tmp/histoire/thumbimage"
  #wkhtmltoimage_cache_dir: "/tmp/histoire/wkhtmltoimage"